version: '3'

services:
  backend:
    image: ge-api:latest
    build:
      context: .
    ports:
      - 5000:3000
    restart: always
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: ge-docker-db